### ISSUE TITLE
建了一個讓js支援多種本地語言的新專案: lingascript

### ISSUE THREAD

**Issue by gasolin** [program-in-chinese/CTS#14]
從CTS和周蟒得到靈感，
LingaScript 除了能讓TypeScript/Javascript支援中文編程，也讓支持擴展到其他非英語編程成為可能。
若能收到其他非英語編程愛好者的協助，中文編程環境也許可以做得更好。

昨天花了一天整理架構，雖與CTS還有一段差距，但初步可測版本已做到：
- 基本的cn關鍵字支持 https://github.com/gasolin/lingascript/blob/master/src/cn/language.ts
- 與typescript本體分離，透過腳本與patch的方式支持不同（自然）語言，更易追隨typescript版本
- cn範例可跑 https://github.com/gasolin/lingascript/blob/master/examples/cn/src/basic.ts
- en/cn基本範例測試通過

希望 @htwx @nobodxbodon 前來指教

連結：https://github.com/gasolin/lingascript

**Comment by nobodxbodon** [comment]
@gasolin 赞!!

[改动](https://github.com/gasolin/lingascript/tree/master/src/common/compiler)的范围很小, 的确会大大简化版本更新. 好像[file-patch](https://libraries.io/npm/file-patch)也支持diff文件的patch? 那样的话, 应该可以更清晰的看到添加/修改的部分吧?

> 也讓支持擴展到其他非英語編程成為可能。
若能收到其他非英語編程愛好者的協助，中文編程環境也許可以做得更好

这是最理想的. 可惜个人暂时没发现母语编程的兴趣组. 也许可以在初步完善后先在国际开发者社区发表一些项目介绍文章?

试运行了一下, 在这里不大确定怎么做: 
> run command `node /built/local/tsc.js` to compile source code in examples/cn with simplified chinese.
```
$ node /built/local/tsc.js examples/cn/src/basic.ts 
module.js:473
      throw err;
      ^

Error: Cannot find module '/built/local/tsc.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```


另外, `npm build:cn`这步应该是`npm run build:cn`吧?

**Comment by gasolin** [comment]
> [改动](https://github.com/gasolin/lingascript/tree/master/src/common/compiler)的范围很小, 的确会大大简化版本更新. 

這只是第一個可運行的版本，現在先搭好框架，確定基本功能達標，之後再擴展守備範圍。

> 好像[file-patch](https://libraries.io/npm/file-patch)也支持diff文件的patch? 那样的话, 应该可以更清晰的看到添加/修改的部分吧?

是的，可以查看 https://github.com/gasolin/lingascript/tree/master/src/common/compiler

> > 也讓支持擴展到其他非英語編程成為可能。
> > 若能收到其他非英語編程愛好者的協助，中文編程環境也許可以做得更好
> 
> 这是最理想的. 可惜个人暂时没发现母语编程的兴趣组. 也许可以在初步完善后先在国际开发者社区发表一些项目介绍文章?

等再完善些可以試試
 
> 试运行了一下, 在这里不大确定怎么做:
> 
> > run command `node /built/local/tsc.js` to compile source code in examples/cn with simplified chinese.
> 

編譯好可以使用以下命令：

```sh
node typescript/built/local/tsc.js -p examples/cn
```

> 另外, `npm build:cn`这步应该是`npm run build:cn`吧?

是的，已更新文檔

**Comment by Akimotorakiyu** [comment]
我并不认为直接patch是一个好的解决方案。
这样并没有足够的灵活性和轻松的可扩展性，甚至还会产生兼容性问题，尤其是在社区对关键字没有统一的标准和定义的时候（类似的情况像js的模块化标准：有Commonjs、AMD、CMD、ES moudle、UMD）
并且，我认为需要同时支持所有语言的关键字和必须是可持续扩展的，因为事实上，需要给出的是一个尽可能的可用于生产的、具有生命力的工业级的解决方式。
