### ISSUE TITLE
最后解决 keyof 及 文字字面量节点 编译2个 问题这个版, 基本就 差不多了

### ISSUE THREAD

**Issue by htwx** [program-in-chinese/CTS#9]

**Comment by nobodxbodon** [comment]
请问这两个问题是用词问题还是技术问题?

**Comment by htwx** [comment]
是 同一个问题  keyof 是 键计算 关键字 他计算完的类型是 个 文字字面量的联合类型 , 
```js
//// [tests/cases/compiler/0.0.1_中文测试集/0004_测试_Ch.ts] ////

//// [index.d.ts]
//@@{ 测试:foo, 属性1:bar, 属性2:baz, 合成属性:nested, 甲:a, 乙:b }
导出 类型 测试 = {
    属性1: 数字 | 空值;
    属性2: 文字;
    合成属性: {
      甲: 数字;
      乙: 文字 | 空值;
    }
  }
    
//// [测试_1.ts]
导入 { 测试 } 来自 "testCh"
  
常量 aFoo: 测试 = { 属性1: 3, 属性2: "b", 合成属性: { 甲: 1, 乙: "y" } };

如果(aFoo && aFoo.合成属性){
    变量 Y = aFoo["合成属性"]["乙"]
    如果(Y === "y"){
          // 解决 keyof 类型计算
    }
}


//// [测试_1.js]
const aFoo = { bar: 3, baz: "b", nested: { a: 1, b: "y" } };
if (aFoo && aFoo.nested) {
    let Y = aFoo["合成属性"]["乙"];
    if (Y === "y") {
        // 解决 keyof 类型计算
    }
}
```

**Comment by htwx** [comment]
```js
let Y = aFoo["合成属性"]["乙"];
<--->
let Y = aFoo["nested"]["b"]     // 这个 "合成属性" 和 "乙" 包含引号就是 字面量类型, 他不是 string 类型
```
上一版的解决方式 通不过 tsc 的测试 , 目前这一版 1\  是 尽量的提高 效率 2\ 是 完全通过 tsc 单元测试.

**Comment by htwx** [comment]
编译的符号是正确的 , 下面是 符号输出的 结果.
```js

如果(aFoo && aFoo.合成属性){
>aFoo : Symbol(aFoo, Decl(测试_1.ts, 2, 2))
>aFoo.合成属性 : Symbol(合成属性, Decl(index.d.ts, 3, 12))
>符号别名 : #合成属性 => nested
>aFoo : Symbol(aFoo, Decl(测试_1.ts, 2, 2))
>合成属性 : Symbol(合成属性, Decl(index.d.ts, 3, 12))
>节点别名 : #合成属性 => nested
>符号别名 : #合成属性 => nested

    变量 Y = aFoo["合成属性"]["乙"]
>Y : Symbol(Y, Decl(测试_1.ts, 5, 6))
>aFoo : Symbol(aFoo, Decl(测试_1.ts, 2, 2))
>"合成属性" : Symbol(合成属性, Decl(index.d.ts, 3, 12))
>节点别名 : #合成属性 => nested
>符号别名 : #合成属性 => nested
>"乙" : Symbol(乙, Decl(index.d.ts, 5, 12))
>节点别名 : #乙 => b
>符号别名 : #乙 => b

    如果(Y === "y"){
>Y : Symbol(Y, Decl(测试_1.ts, 5, 6))

          // 解决 keyof 类型计算
    }
}
```

**Comment by htwx** [comment]
编译的类型也是是正确的 , 下面是 类型 输出的 结果.
```js

如果(aFoo && aFoo.合成属性){
>aFoo && aFoo.合成属性 : { 甲: number; 乙: string | null; }
>aFoo : 测试
>aFoo.合成属性 : { 甲: number; 乙: string | null; }
>aFoo : 测试
>合成属性 : { 甲: number; 乙: string | null; }

    变量 Y = aFoo["合成属性"]["乙"]
>Y : string | null
>aFoo["合成属性"]["乙"] : string | null
>aFoo["合成属性"] : { 甲: number; 乙: string | null; }
>aFoo : 测试
>"合成属性" : "合成属性"
>"乙" : "乙"

    如果(Y === "y"){
>Y === "y" : boolean
>类型别名 :=> 真假
>Y : string | null
>"y" : "y"

          // 解决 keyof 类型计算
    }
}

```

**Comment by htwx** [comment]
编译的js 文件还不是是正确的 , 下面是js编译测试结果
```js
//// [tests/cases/compiler/0.0.1_中文测试集/0004_测试_Ch.ts] ////

//// [index.d.ts]
//@@{ 测试:foo, 属性1:bar, 属性2:baz, 合成属性:nested, 甲:a, 乙:b }
导出 类型 测试 = {
    属性1: 数字 | 空值;
    属性2: 文字;
    合成属性: {
      甲: 数字;
      乙: 文字 | 空值;
    }
  }
    
//// [测试_1.ts]
导入 { 测试 } 来自 "testCh"
  
常量 aFoo: 测试 = { 属性1: 3, 属性2: "b", 合成属性: { 甲: 1, 乙: "y" } };

如果(aFoo && aFoo.合成属性){
    变量 Y = aFoo["合成属性"]["乙"]
    如果(Y === "y"){
          // 解决 keyof 类型计算
    }
}


//// [测试_1.js]
const aFoo = { bar: 3, baz: "b", nested: { a: 1, b: "y" } };
if (aFoo && aFoo.nested) {
    let Y = aFoo["合成属性"]["乙"];   // 这里的 "合成属性"  和 "乙" 应该输出 对应的 别名
    if (Y === "y") {
        // 解决 keyof 类型计算
    }
}
```

**Comment by htwx** [comment]
前一段时间 基本就解决  解构 的问题了.

**Comment by htwx** [comment]
```js

  57790 passing (11m)
  12 failing

  1) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0001_测试_Ch.ts
         Correct JS output for tests/cases/compiler/0.0.1_中文测试集/0001_测试_Ch.ts:
     Error: The baseline file 0001_测试_Ch.js has changed.
      at writeComparison (src\harness\harness.ts:2063:23)
      at Object.runBaseline (src\harness\harness.ts:2071:13)
      at Object.doJsEmitBaseline (src\harness\harness.ts:1633:30)
      at Context.<anonymous> (src\harness\compilerRunner.ts:167:38)

  2) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0001_测试_Ch.ts
         Correct type/symbol baselines for tests/cases/compiler/0.0.1_中文测试集/0001_测试_Ch.ts:
     Error: The baseline file 0001_测试_Ch.types has changed.
The baseline file 0001_测试_Ch.symbols has changed.
      at Object.doTypeAndSymbolBaseline (src\harness\harness.ts:1495:23)
      at Context.<anonymous> (src\harness\compilerRunner.ts:180:34)

  3) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0001_测试_En.ts
         Correct JS output for tests/cases/compiler/0.0.1_中文测试集/0001_测试_En.ts:
     Error: The baseline file 0001_测试_En.js has changed.
      at writeComparison (src\harness\harness.ts:2063:23)
      at Object.runBaseline (src\harness\harness.ts:2071:13)
      at Object.doJsEmitBaseline (src\harness\harness.ts:1633:30)
      at Context.<anonymous> (src\harness\compilerRunner.ts:167:38)

  4) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0001_测试_En.ts
         Correct type/symbol baselines for tests/cases/compiler/0.0.1_中文测试集/0001_测试_En.ts:
     Error: The baseline file 0001_测试_En.types has changed.
The baseline file 0001_测试_En.symbols has changed.
      at Object.doTypeAndSymbolBaseline (src\harness\harness.ts:1495:23)
      at Context.<anonymous> (src\harness\compilerRunner.ts:180:34)

  5) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0002_测试_ch.ts
         Correct JS output for tests/cases/compiler/0.0.1_中文测试集/0002_测试_ch.ts:
     Error: The baseline file 0002_测试_ch.js has changed.
      at writeComparison (src\harness\harness.ts:2063:23)
      at Object.runBaseline (src\harness\harness.ts:2071:13)
      at Object.doJsEmitBaseline (src\harness\harness.ts:1633:30)
      at Context.<anonymous> (src\harness\compilerRunner.ts:167:38)

  6) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0002_测试_ch.ts
         Correct type/symbol baselines for tests/cases/compiler/0.0.1_中文测试集/0002_测试_ch.ts:
     Error: The baseline file 0002_测试_ch.types has changed.
The baseline file 0002_测试_ch.symbols has changed.
      at Object.doTypeAndSymbolBaseline (src\harness\harness.ts:1495:23)
      at Context.<anonymous> (src\harness\compilerRunner.ts:180:34)

  7) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0003_测试_ch.ts
         Correct errors for tests/cases/compiler/0.0.1_中文测试集/0003_测试_ch.ts:
     Error: The baseline file 0003_测试_ch.errors.txt has changed.
      at writeComparison (src\harness\harness.ts:2063:23)
      at Object.runBaseline (src\harness\harness.ts:2071:13)
      at Object.doErrorBaseline (src\harness\harness.ts:1449:30)
      at Context.<anonymous> (src\harness\compilerRunner.ts:138:34)

  8) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0003_测试_ch.ts
         Correct JS output for tests/cases/compiler/0.0.1_中文测试集/0003_测试_ch.ts:
     Error: The baseline file 0003_测试_ch.js has changed.
      at writeComparison (src\harness\harness.ts:2063:23)
      at Object.runBaseline (src\harness\harness.ts:2071:13)
      at Object.doJsEmitBaseline (src\harness\harness.ts:1633:30)
      at Context.<anonymous> (src\harness\compilerRunner.ts:167:38)

  9) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0003_测试_ch.ts
         Correct type/symbol baselines for tests/cases/compiler/0.0.1_中文测试集/0003_测试_ch.ts:
     Error: The baseline file 0003_测试_ch.types has changed.
The baseline file 0003_测试_ch.symbols has changed.
      at Object.doTypeAndSymbolBaseline (src\harness\harness.ts:1495:23)
      at Context.<anonymous> (src\harness\compilerRunner.ts:180:34)

  10) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0004_测试_Ch.ts
         Correct JS output for tests/cases/compiler/0.0.1_中文测试集/0004_测试_Ch.ts:
     Error: The baseline file 0004_测试_Ch.js has changed.
      at writeComparison (src\harness\harness.ts:2063:23)
      at Object.runBaseline (src\harness\harness.ts:2071:13)
      at Object.doJsEmitBaseline (src\harness\harness.ts:1633:30)
      at Context.<anonymous> (src\harness\compilerRunner.ts:167:38)

  11) compiler tests
       compiler tests for tests/cases/compiler/0.0.1_中文测试集/0004_测试_Ch.ts
         Correct type/symbol baselines for tests/cases/compiler/0.0.1_中文测试集/0004_测试_Ch.ts:
     Error: The baseline file 0004_测试_Ch.types has changed.
The baseline file 0004_测试_Ch.symbols has changed.
      at Object.doTypeAndSymbolBaseline (src\harness\harness.ts:1495:23)
      at Context.<anonymous> (src\harness\compilerRunner.ts:180:34)

  12) Public APIs
       for the language service and compiler
         should be acknowledged when they change:
     Error: The baseline file api/typescript.d.ts has changed.
      at writeComparison (src\harness\harness.ts:2063:23)
      at Object.runBaseline (src\harness\harness.ts:2071:13)
      at Context.<anonymous> (src\harness\unittests\publicApi.ts:13:30)


```

**Comment by htwx** [comment]
57790 passing (11m)   
近 6 万的 测试 及输出 才 11 分钟 ,我觉得 真不慢了 比 官方原版 慢了一点点.
这 12个不是 错误 是我没有 合并 测试结果.

**Comment by htwx** [comment]
这个慢只是 编译的速度慢了, 不影响编译完的 程序运行速度.

**Comment by htwx** [comment]
都说 语言和 语言无关 
```js
//// [测试_1.ts]
导入 { 测试 } 来自 "testCh"
  
常量 aFoo: 测试 = { 属性1: 3, 属性2: "b", 合成属性: { 甲: 1, 乙: "y" } };

如果(aFoo && aFoo.合成属性){
    变量 Y = aFoo["合成属性"]["乙"]
    如果(Y === "y"){
          // 解决 keyof 类型计算
    }
}
```
要按目前来说 我这个是标准的 英文编程.
变量名都是 英文的

**Comment by nobodxbodon** [comment]
> 前一段时间 基本就解决 解构 的问题了.

请问`解构`是指...?

> 要按目前来说 我这个是标准的 英文编程.
变量名都是 英文的

呵呵呵 中文关键词+英文变量名确实有点违和啊 不过没毛病. 反正中文变量名支持就行.

**Comment by nobodxbodon** [comment]
不知[会上](https://github.com/program-in-chinese/overview/issues/127#issuecomment-453729791)提到的是这个问题吗? 还是与https://github.com/program-in-chinese/CTS/issues/8 更相关?
